"""
Synthetic Transaction Data Generator (Production-Grade)
=========================================================
Generates realistic, weighted, noisy synthetic financial transactions
for training a TF-IDF + ML text classifier (auto-categorization) in the
Budget Tracker Django app.

Run inside a Django shell / management command:
    python manage.py shell < generate_transactions.py
or import generate_data() from a custom management command.

FIX APPLIED vs. original version:
    All synthetic rows now belong to a dedicated "ml_training_bot" user
    (created automatically if it doesn't exist) instead of
    User.objects.first(). The original version dumped 10,000 fake rows
    onto whichever account happened to be first in the DB — almost
    certainly your own real testing account — which would flood your
    Dashboard, History, Analysis, Budgets, and CSV export with garbage
    data, since every view filters by Transaction.objects.filter(user=
    request.user).

    training data doesn't need to belong to your real user: data_prep.py
    reads Transaction.objects.all() with NO user filter, so the model
    trains on this data regardless of which account owns it.
"""

import random
from datetime import date, timedelta

from django.contrib.auth.models import User

from Budget.models import Category, Transaction

# -----------------------------------------------------------------------
# 0. DEDICATED TRAINING USER
# -----------------------------------------------------------------------
# All synthetic transactions are attached to this account, never to a
# real user, so nobody's Dashboard/History/Budgets/exports get polluted.
TRAINING_USERNAME = "ml_training_bot"

# -----------------------------------------------------------------------
# 1. CATEGORY -> DESCRIPTION TEMPLATES (50 realistic variations each)
# -----------------------------------------------------------------------
CATEGORIES = {
    "Food": [
        "Dinner at Subway",
        "Costa Coffee Purchase",
        "Cinnabon Purchase",
        "Lunch at Subway",
        "Tim Hortons Purchase",
        "Lunch at Abou Tarek",
        "Cilantro Restaurant Order",
        "Dinner at McDonald's",
        "Dinner at Pizza Hut",
        "Lunch at Zooba",
        "Lunch at Gad",
        "Lunch at Papa John's",
        "Lunch at Cilantro Restaurant",
        "Dinner at Gad",
        "Grand Cafe Purchase",
        "Chipotle Order",
        "Mo'men Order",
        "Buffalo Burger Order",
        "KFC Order",
        "Dinner at Chipotle",
        "Five Guys Order",
        "Lunch at Felfela",
        "Wendy's Order",
        "Dinner at KFC",
        "Coffee at Costa Coffee",
        "Takeout Order",
        "Cilantro Cafe Purchase",
        "Dinner at Papa John's",
        "Coffee at Lavazza",
        "Dinner at Buffalo Burger",
        "Harrys Pub Cafe Purchase",
        "Subway Order",
        "Abou Tarek Order",
        "Dinner at Felfela",
        "Lunch at McDonald's",
        "Gad Order",
        "Felfela Order",
        "Pizza Hut Order",
        "Dinner at Shawarmer",
        "Zooba Order",
        "Lunch at Shawarmer",
        "Coffee at Harrys Pub Cafe",
        "Elmenus Order",
        "Lunch at Burger King",
        "Beano's Cafe Purchase",
        "Coffee at Grand Cafe",
        "Coffee at Cilantro Cafe",
        "Espresso Lab Purchase",
        "Al Tazaj Order",
        "Dinner at Wendy's",
    ],
    "Transport": [
        "InDrive Trip",
        "City Cab Ride to Mall",
        "InDrive Fare Payment",
        "Swvl Fare Payment",
        "Halan Fare Payment",
        "Car Rental Payment",
        "City Cab Late Night Ride",
        "Ride via InDrive",
        "Ride via Swvl",
        "Uber Fare Payment",
        "Ride via Careem",
        "Toll Road Payment",
        "Cairo Metro Ticket",
        "Parking Fee Payment",
        "Airport Transfer Taxi",
        "Careem Late Night Ride",
        "Halan Late Night Ride",
        "Ride via Didi",
        "Careem Airport Transfer",
        "Public Transport Card",
        "Cab Ride",
        "Train Ticket Payment",
        "City Cab Trip",
        "Ride via City Cab",
        "Careem Trip",
        "Taxi Fare Payment",
        "Swvl Airport Transfer",
        "Halan Ride to Mall",
        "Uber Airport Transfer",
        "InDrive Late Night Ride",
        "Halan Airport Transfer",
        "Careem Ride to Mall",
        "Halan Ride",
        "Ride to Airport",
        "InDrive Airport Transfer",
        "Uber Trip",
        "Swvl Trip",
        "Careem Fare Payment",
        "Ride to Work",
        "Ride via Uber",
        "InDrive Ride to Mall",
        "Rental Car Booking",
        "Didi Late Night Ride",
        "Careem Ride",
        "Halan Trip",
        "Swvl Ride to Mall",
        "Didi Fare Payment",
        "Ride via Halan",
        "Uber Ride",
        "Bus Fare Payment",
    ],
    "Shopping": [
        "AliExpress Order",
        "Jumia Checkout",
        "Shopping at Souq.com",
        "Amazon Purchase",
        "Noon Checkout",
        "Shein Online Order",
        "Temu Online Order",
        "Temu Purchase",
        "Etsy Online Order",
        "Souq.com Online Order",
        "Wadi.com Purchase",
        "Shopping at Temu",
        "Shopping at Wadi.com",
        "Shopping at Amazon",
        "Wadi.com Order",
        "Temu Checkout",
        "Souq.com Purchase",
        "eBay Online Order",
        "Etsy Checkout",
        "Shopping at AliExpress",
        "Shopping at Noon",
        "Shopping at Jumia",
        "Shein Purchase",
        "Souq.com Order",
        "AliExpress Purchase",
        "eBay Order",
        "Wadi.com Checkout",
        "Jumia Order",
        "Jumia Purchase",
        "Shein Order",
        "Shopping at eBay",
        "Noon Purchase",
        "Shopping at Etsy",
        "Souq.com Checkout",
        "Etsy Purchase",
        "eBay Checkout",
        "AliExpress Online Order",
        "Amazon Order",
        "Shein Checkout",
        "Amazon Online Order",
        "Shopping at Shein",
        "eBay Purchase",
        "Noon Order",
        "Jumia Online Order",
        "Amazon Checkout",
        "Etsy Order",
        "Temu Order",
        "AliExpress Checkout",
        "Wadi.com Online Order",
        "Noon Online Order",
    ],
    "Bills": [
        "Credit Card Bill Payment",
        "QNB Alahli Credit Card Bill",
        "HSBC Monthly Fee",
        "National Bank of Egypt Credit Card Bill",
        "Banque Misr Monthly Fee",
        "CIB Bank Monthly Fee",
        "Vodafone Phone Bill Payment",
        "Landline Bill Payment",
        "Parking Subscription Fee",
        "QNB Alahli Monthly Fee",
        "Internet Overage Fee",
        "Mobile Bill Etisalat",
        "Mobile Bill Vodafone",
        "Check Book Issuance Fee",
        "Mobile Bill Orange",
        "Postpaid Phone Bill",
        "CIB Bank Account Maintenance Fee",
        "Orange Phone Bill Payment",
        "CIB Bank Credit Card Bill",
        "Bank Service Fee",
        "Etisalat Phone Bill Payment",
        "HSBC Credit Card Bill",
        "Property Tax Payment",
        "Banque Misr Account Maintenance Fee",
        "HSBC Account Maintenance Fee",
        "Elevator Maintenance Fee",
        "Utility Reconnection Fee",
        "Annual Membership Fee",
        "Building Maintenance Fee",
        "HOA Fee Payment",
        "National Bank of Egypt Monthly Fee",
        "Mobile Data Overage Charge",
        "Card Replacement Fee",
        "TV Cable Subscription Bill",
        "Security Service Fee",
        "Municipal Tax Payment",
        "Mobile Bill WE",
        "WE Phone Bill Payment",
        "Home Maintenance Fee",
        "Gas Bill Payment",
        "Satellite TV Bill",
        "National Bank of Egypt Account Maintenance Fee",
        "Late Payment Fee",
        "Bank Wire Transfer Fee",
        "Waste Collection Fee",
        "Monthly Bill Payment",
        "QNB Alahli Account Maintenance Fee",
        "Prepaid Line Recharge",
        "ATM Withdrawal Fee",
        "Service Bill Payment",
    ],
    "Entertainment": [
        "Circus Show Tickets",
        "Escape Room Booking",
        "Monthly HBO Max",
        "Steam Game Purchase",
        "Water Park Tickets",
        "Monthly Amazon Prime Video",
        "PlayStation Store Purchase",
        "Nightclub Entry Fee",
        "Shahid Subscription",
        "Watch iT Subscription",
        "Apple Music Subscription",
        "Xbox Game Pass Payment",
        "Vox Cinemas Ticket",
        "Zoo Entry Tickets",
        "Go Kart Racing Payment",
        "Monthly Shahid",
        "Football Match Tickets",
        "Netflix Subscription",
        "Spotify Subscription",
        "Arcade Games Payment",
        "Monthly Spotify",
        "Monthly Watch iT",
        "Monthly Netflix",
        "Live Concert Tickets",
        "Video Game Purchase",
        "Monthly Disney+",
        "Magic Planet Entry",
        "Amusement Park Entry",
        "Anghami Subscription",
        "Laser Tag Session",
        "Karting Entry Fee",
        "Cinema City Ticket",
        "Dream Park Tickets",
        "OSN Subscription",
        "HBO Max Subscription",
        "Monthly OSN",
        "VR Gaming Experience",
        "Trampoline Park Entry",
        "Comedy Show Tickets",
        "YouTube Premium Subscription",
        "Monthly YouTube Premium",
        "Monthly Apple Music",
        "Bowling Night Payment",
        "Concert Ticket Purchase",
        "Movie Tickets Cinema",
        "Disney+ Subscription",
        "Museum Entry Fee",
        "Monthly Anghami",
        "Theater Show Tickets",
        "Amazon Prime Video Subscription",
    ],
    "Healthcare": [
        "Medicine Purchase Misr Pharmacy",
        "Doctor Visit As-Salam International Hospital",
        "Andalusia Hospital Payment",
        "El Salam Hospital Payment",
        "Cairo Medical Center Payment",
        "Medicine Purchase 19011 Pharmacy",
        "Doctor Visit Andalusia Hospital",
        "Eye Clinic Checkup",
        "Ultrasound Payment",
        "Cleopatra Hospital Payment",
        "Ibrahim Pharmacy Purchase",
        "Blood Test Payment",
        "Emergency Room Visit",
        "Doctor Visit Al Ahly Medical Clinic",
        "MRI Scan Payment",
        "Lab Test Payment",
        "Doctor Visit El Salam Hospital",
        "Skin Clinic Visit",
        "Doctor Visit Nile Badrawi Hospital",
        "Vaccination Payment",
        "Physiotherapy Session Payment",
        "Nile Badrawi Hospital Payment",
        "Doctor Visit Al Mokhtabar Labs",
        "Dar Al Fouad Hospital Payment",
        "As-Salam International Hospital Payment",
        "Mental Health Session Payment",
        "Seif Pharmacy Purchase",
        "X-Ray Scan Payment",
        "Dental Clinic Payment",
        "Orthodontist Payment",
        "Medicine Purchase Ibrahim Pharmacy",
        "Ain Shams University Hospital Payment",
        "Doctor Visit El Nasr Medical Clinic",
        "Medicine Purchase El Ezaby Pharmacy",
        "Dr. Mona Clinic Payment",
        "Doctor Visit Dr. Mona Clinic",
        "Doctor Visit Ain Shams University Hospital",
        "Al Mokhtabar Labs Payment",
        "Medicine Purchase Roshdy Pharmacy",
        "Roshdy Pharmacy Purchase",
        "Medicine Purchase Seif Pharmacy",
        "El Nasr Medical Clinic Payment",
        "Doctor Visit Cleopatra Hospital",
        "Health Checkup Payment",
        "19011 Pharmacy Purchase",
        "El Ezaby Pharmacy Purchase",
        "Misr Pharmacy Purchase",
        "Medicine Purchase Pharmacy One",
        "Doctor Visit Dar Al Fouad Hospital",
        "Doctor Visit Cairo Medical Center",
    ],
    "Education": [
        "University Tuition German University in Cairo",
        "edX Course Payment",
        "Helwan University Tuition Payment",
        "Kotobna Bookstore Purchase",
        "Textbook Purchase Barnes & Noble",
        "American University in Cairo Tuition Payment",
        "University Tuition American University in Cairo",
        "Textbook Purchase Nahdet Misr Bookstore",
        "Shorouk Bookstore Purchase",
        "University Tuition British University in Egypt",
        "Private Tutoring Fee",
        "British University in Egypt Tuition Payment",
        "Alexandria University Tuition Payment",
        "University Tuition Future University",
        "Cairo British School School Fees",
        "Nahdet Misr Bookstore Purchase",
        "Future University Tuition Payment",
        "Textbook Purchase Kotobna Bookstore",
        "University Tuition MSA University",
        "Coursera Subscription",
        "LinkedIn Learning Subscription",
        "Exam Fee Payment",
        "Language Course Payment",
        "University Tuition Nile University",
        "German University in Cairo Tuition Payment",
        "Nile University Tuition Payment",
        "Diwan Bookstore Purchase",
        "University Tuition Ahram Canadian University",
        "Modern English School School Fees",
        "Udemy Course Purchase",
        "Textbook Purchase Diwan Bookstore",
        "Online Course Payment Coursera",
        "School Uniform Purchase",
        "MSA University Tuition Payment",
        "Ain Shams University Tuition Payment",
        "El Manar School School Fees",
        "Cairo University Tuition Payment",
        "Alef Bookstore Purchase",
        "Textbook Purchase Alef Bookstore",
        "University Tuition Cairo University",
        "Textbook Purchase Shorouk Bookstore",
        "New Cairo British International School School Fees",
        "School Bus Fee",
        "University Tuition Helwan University",
        "Certification Exam Fee",
        "Student ID Renewal Fee",
        "University Tuition Alexandria University",
        "University Tuition Ain Shams University",
        "Ahram Canadian University Tuition Payment",
        "Udemy Course Payment",
    ],
    "Groceries": [
        "Alfa Market Weekly Shopping",
        "Lulu Hypermarket Weekly Shopping",
        "Kazyon Grocery Order",
        "Panda Retail Weekly Shopping",
        "Fathalla Market Weekly Shopping",
        "Groceries from Spinneys",
        "Groceries from Metro Market",
        "Metro Market Weekly Shopping",
        "Groceries from Gourmet Egypt",
        "Carrefour Grocery Order",
        "Awlad Ragab Grocery Order",
        "Shopping at Kheir Zaman",
        "Shopping at Spinneys",
        "Ragab Sons Weekly Shopping",
        "Shopping at Fathalla Market",
        "Shopping at Bim Egypt",
        "Kazyon Weekly Shopping",
        "Fathalla Market Grocery Order",
        "Bim Egypt Grocery Order",
        "Panda Retail Grocery Order",
        "Spinneys Weekly Shopping",
        "Shopping at Kazyon",
        "Carrefour Weekly Shopping",
        "Groceries from Bim Egypt",
        "Ragab Sons Grocery Order",
        "Groceries from Awlad Ragab",
        "Awlad Ragab Weekly Shopping",
        "Zahran Market Grocery Order",
        "Metro Market Grocery Order",
        "Seoudi Market Grocery Order",
        "Shopping at Ragab Sons",
        "Hyper One Grocery Order",
        "Shopping at Carrefour",
        "Groceries from Seoudi Market",
        "Hyper One Weekly Shopping",
        "Bim Egypt Weekly Shopping",
        "Shopping at Seoudi Market",
        "Shopping at Lulu Hypermarket",
        "Gourmet Egypt Weekly Shopping",
        "Shopping at Gourmet Egypt",
        "Kheir Zaman Grocery Order",
        "Shopping at Zahran Market",
        "Shopping at Metro Market",
        "Groceries from Fathalla Market",
        "Alfa Market Grocery Order",
        "Zahran Market Weekly Shopping",
        "Groceries from Zahran Market",
        "Groceries from Hyper One",
        "Groceries from Ragab Sons",
        "Groceries from Lulu Hypermarket",
    ],
    "Income": [
        "Gift Money Received",
        "Contract Payment ACME Corp",
        "Payment from Pfizer Egypt",
        "Grant Payment Received",
        "Refund Received",
        "Bonus Payment",
        "Overtime Pay",
        "Year End Bonus",
        "Payment from Valeo Egypt",
        "Investment Return",
        "Contract Payment ITWorx",
        "Payment from Instabug",
        "Payment from Google",
        "Payment from IBM Egypt",
        "Payment from ITWorx",
        "Upwork Freelance Payment",
        "Payment from Fawry",
        "Contract Payment Microsoft",
        "Referral Bonus Received",
        "Payment from Schneider Electric Egypt",
        "Contract Payment Raya Holding",
        "Payment from Vodafone Egypt",
        "Reimbursement Received",
        "Contract Payment Nestle Egypt",
        "Payment from Raya Holding",
        "Side Project Income",
        "Payment from EgyptAir",
        "Contract Payment Instabug",
        "Payment from Etisalat Misr",
        "Royalty Payment",
        "Contract Payment Fawry",
        "Loan Repayment Received",
        "Tax Refund",
        "Cashback Payment",
        "Freelance Payment Received",
        "Fiverr Payment Received",
        "Contract Payment Pfizer Egypt",
        "Performance Bonus",
        "Payment from Nestle Egypt",
        "Commission Payment Received",
        "Contract Payment Valeo Egypt",
        "Contract Payment Vodafone Egypt",
        "Freelance Invoice Payment",
        "Contract Payment Etisalat Misr",
        "Prize Money Received",
        "Payment from Orange Business",
        "Contract Payment Google",
        "Rental Income Received",
        "Payment from ACME Corp",
        "Consulting Fee Received",
    ],
    "Travel": [
        "Flight Booking Air Arabia",
        "Passport Renewal Fee",
        "Travel Insurance Purchase",
        "Qatar Airways Flight Ticket",
        "Booking.com Hotel Reservation",
        "Emirates Flight Ticket",
        "Visa Application Fee",
        "Flight to Dubai",
        "Flight Booking Lufthansa",
        "Flight to Jeddah",
        "Flight Booking flydubai",
        "Train Trip Booking Europe",
        "Ski Trip Booking",
        "Flight Booking British Airways",
        "Expedia Travel Booking",
        "Etihad Airways Flight Ticket",
        "Saudia Flight Ticket",
        "Flight Booking Qatar Airways",
        "British Airways Flight Ticket",
        "Baggage Fee Payment",
        "Airport Lounge Access",
        "Flight Booking Turkish Airlines",
        "EgyptAir Flight Ticket",
        "Flight to Riyadh",
        "Flight Booking Air Cairo",
        "Flight Booking Nile Air",
        "Airbnb Reservation Payment",
        "Turkish Airlines Flight Ticket",
        "Resort Booking Payment",
        "Flight to London",
        "Tour Package Payment",
        "Flight to Istanbul",
        "Air Arabia Flight Ticket",
        "Flight to Doha",
        "Rental Car Abroad Payment",
        "Hotel Booking Payment",
        "Vacation Package Payment",
        "Flight Booking Emirates",
        "Beach Resort Reservation",
        "Nile Air Flight Ticket",
        "Ferry Ticket Booking",
        "Flight Booking Saudia",
        "Tour Guide Fee",
        "Lufthansa Flight Ticket",
        "Travel SIM Card Purchase",
        "flydubai Flight Ticket",
        "Flight Booking Etihad Airways",
        "Travel Agency Booking",
        "Flight Booking EgyptAir",
        "Air Cairo Flight Ticket",
    ],
    "Subscriptions": [
        "News Subscription Payment",
        "Magazine Subscription Renewal",
        "Disney+ Annual Subscription",
        "Netflix Monthly Plan",
        "Anghami Annual Subscription",
        "YouTube Premium Premium",
        "YouTube Premium Renewal",
        "Cloud Storage Subscription",
        "Spotify Monthly Plan",
        "HBO Max Premium",
        "Anghami Monthly Plan",
        "Microsoft 365 Subscription",
        "YouTube Premium Monthly Plan",
        "Spotify Renewal",
        "Netflix Renewal",
        "Apple Music Premium",
        "Anghami Premium",
        "HBO Max Annual Subscription",
        "Watch iT Monthly Plan",
        "Spotify Premium",
        "Spotify Annual Subscription",
        "HBO Max Monthly Plan",
        "Disney+ Premium",
        "Shahid Annual Subscription",
        "Disney+ Monthly Plan",
        "Google One Subscription",
        "Watch iT Renewal",
        "Watch iT Annual Subscription",
        "OSN Renewal",
        "Amazon Prime Video Annual Subscription",
        "Watch iT Premium",
        "Shahid Renewal",
        "Shahid Premium",
        "OSN Monthly Plan",
        "Apple Music Renewal",
        "Amazon Prime Video Renewal",
        "iCloud Storage Payment",
        "Adobe Creative Cloud Subscription",
        "Gym Membership Renewal",
        "Amazon Prime Video Monthly Plan",
        "Netflix Annual Subscription",
        "Shahid Monthly Plan",
        "HBO Max Renewal",
        "Disney+ Renewal",
        "Anghami Renewal",
        "Amazon Prime Video Premium",
        "YouTube Premium Annual Subscription",
        "OSN Premium",
        "Netflix Premium",
        "Apple Music Annual Subscription",
    ],
    "Insurance": [
        "MetLife Premium Payment",
        "AXA Insurance Dental Plan Premium",
        "Home Insurance Payment",
        "Bupa Global Policy Renewal",
        "MetLife Annual Premium",
        "MetLife Dental Plan Premium",
        "Misr Insurance Dental Plan Premium",
        "Bupa Global Dental Plan Premium",
        "GIG Insurance Annual Premium",
        "Bupa Global Home Insurance Payment",
        "Nile Insurance Company Dental Plan Premium",
        "Health Insurance Premium Allianz Egypt",
        "Health Insurance Premium Nile Insurance Company",
        "Nile Insurance Company Premium Payment",
        "Car Insurance AXA Insurance",
        "Business Insurance Payment",
        "Allianz Egypt Policy Renewal",
        "Car Insurance Bupa Global",
        "Misr Insurance Premium Payment",
        "Health Insurance Premium MetLife",
        "AXA Insurance Premium Payment",
        "MetLife Policy Renewal",
        "Misr Insurance Annual Premium",
        "Health Insurance Premium GIG Insurance",
        "GIG Insurance Policy Renewal",
        "Health Insurance Premium Bupa Global",
        "Life Insurance Payment",
        "Property Insurance Premium",
        "Dental Insurance Premium",
        "Motor Insurance Renewal",
        "Nile Insurance Company Policy Renewal",
        "Allianz Egypt Dental Plan Premium",
        "Car Insurance Allianz Egypt",
        "Pet Insurance Payment",
        "Car Insurance Nile Insurance Company",
        "Allianz Egypt Annual Premium",
        "GIG Insurance Dental Plan Premium",
        "AXA Insurance Policy Renewal",
        "Travel Insurance Payment",
        "GIG Insurance Home Insurance Payment",
        "Nile Insurance Company Home Insurance Payment",
        "Misr Insurance Policy Renewal",
        "GIG Insurance Premium Payment",
        "Allianz Egypt Home Insurance Payment",
        "Health Insurance Premium AXA Insurance",
        "Car Insurance MetLife",
        "Health Insurance Premium Misr Insurance",
        "Misr Insurance Home Insurance Payment",
        "Nile Insurance Company Annual Premium",
        "AXA Insurance Home Insurance Payment",
    ],
    "Investment": [
        "Interactive Brokers Investment Deposit",
        "EFG Hermes Portfolio Deposit",
        "Stock Purchase Interactive Brokers",
        "Vanguard Trading Account Deposit",
        "Stock Purchase eToro",
        "Beltone Financial Trading Account Deposit",
        "Vanguard Investment Deposit",
        "Dividend Payment Robinhood",
        "Dividend Payment Vanguard",
        "Fidelity Investments Trading Account Deposit",
        "Sarwa Invest Investment Deposit",
        "Vanguard Portfolio Deposit",
        "Stock Purchase Robinhood",
        "Bond Purchase",
        "Dividend Payment Fidelity Investments",
        "Beltone Financial Portfolio Deposit",
        "CI Capital Investment Deposit",
        "Stock Purchase Thndr",
        "ETF Purchase",
        "Sarwa Invest Portfolio Deposit",
        "Sarwa Invest Trading Account Deposit",
        "Dividend Payment Beltone Financial",
        "EFG Hermes Trading Account Deposit",
        "eToro Investment Deposit",
        "Dividend Payment eToro",
        "Stock Purchase Fidelity Investments",
        "Stock Purchase CI Capital",
        "Dividend Payment EFG Hermes",
        "Robinhood Investment Deposit",
        "Interactive Brokers Portfolio Deposit",
        "Dividend Payment Sarwa Invest",
        "eToro Trading Account Deposit",
        "EFG Hermes Investment Deposit",
        "Stock Purchase Sarwa Invest",
        "Robinhood Portfolio Deposit",
        "Dividend Payment CI Capital",
        "Stock Purchase Beltone Financial",
        "Interactive Brokers Trading Account Deposit",
        "CI Capital Trading Account Deposit",
        "Robinhood Trading Account Deposit",
        "Certificate of Deposit Investment",
        "Thndr Investment Deposit",
        "Fidelity Investments Investment Deposit",
        "eToro Portfolio Deposit",
        "Crypto Purchase",
        "Mutual Fund Investment",
        "Dividend Payment Interactive Brokers",
        "Thndr Trading Account Deposit",
        "Stock Purchase EFG Hermes",
        "CI Capital Portfolio Deposit",
    ],
    "Salary": [
        "Monthly Salary Nestle Egypt",
        "Microsoft Payroll",
        "Salary June",
        "Salary January",
        "Monthly Salary Raya Holding",
        "Payroll Deposit Instabug",
        "Monthly Salary Pfizer Egypt",
        "Salary Google",
        "Salary Payment May",
        "Vodafone Egypt Payroll",
        "Salary ACME Corp",
        "Monthly Salary Fawry",
        "Valeo Egypt Payroll",
        "Pfizer Egypt Payroll",
        "Instabug Payroll",
        "Careem Egypt Payroll",
        "Salary Payment October",
        "Payroll Deposit Fawry",
        "Monthly Salary Careem Egypt",
        "Payroll Deposit Valeo Egypt",
        "Salary Fawry",
        "Salary Raya Holding",
        "Salary Payment June",
        "Monthly Salary Orange Business",
        "Salary September",
        "Salary Payment April",
        "Schneider Electric Egypt Payroll",
        "Salary Valeo Egypt",
        "Salary Payment February",
        "Salary Payment November",
        "Salary October",
        "Payroll Deposit EgyptAir",
        "Salary Schneider Electric Egypt",
        "Monthly Salary Instabug",
        "Payroll Deposit Cairo University",
        "Salary Cairo University",
        "Fawry Payroll",
        "Salary Pfizer Egypt",
        "Payroll Deposit Careem Egypt",
        "Salary Etisalat Misr",
        "Orange Business Payroll",
        "Monthly Salary Cairo University",
        "Salary December",
        "Salary Careem Egypt",
        "Payroll Deposit IBM Egypt",
        "ACME Corp Payroll",
        "Salary May",
        "Salary Payment January",
        "Cairo University Payroll",
        "Salary Instabug",
    ],
    "Utilities": [
        "WiFi Subscription Payment",
        "South Cairo Electricity Company Electricity Invoice",
        "Alexandria Water Company Water Invoice",
        "WE Internet Monthly Fee",
        "Generator Fuel Utility Charge",
        "Electricity Payment Cairo Electricity Distribution Company",
        "Electricity Meter Top Up",
        "Fiber Optic Installation Fee",
        "Internet Bill WE Internet",
        "Water Bill Settlement",
        "Water Bill Payment",
        "Internet Bill TE Data",
        "Internet Bill Orange Home Fiber",
        "Electricity Bill Payment",
        "Prepaid Water Meter Recharge",
        "TE Data Monthly Fee",
        "Water Meter Top Up",
        "Water Payment Alexandria Water Company",
        "District Cooling Bill",
        "Water Payment Cairo Water Company",
        "Cairo Water Company Water Invoice",
        "Egyptian Electricity Holding Company Electricity Invoice",
        "Electricity Payment North Cairo Electricity Company",
        "Water Payment Holding Company for Water and Wastewater",
        "Landline Line Rental Fee",
        "Solar Panel Maintenance Fee",
        "Electricity Bill Settlement",
        "Community Utility Share Fee",
        "Electricity Payment Egyptian Electricity Holding Company",
        "Orange Home Fiber Monthly Fee",
        "Cable Modem Rental Fee",
        "Vodafone Home Internet Monthly Fee",
        "Holding Company for Water and Wastewater Water Invoice",
        "North Cairo Electricity Company Electricity Invoice",
        "Electricity Payment South Cairo Electricity Company",
        "Internet Bill Vodafone Home Internet",
        "Sewage Service Fee",
        "Trash Collection Bill",
        "Noor ADSL Monthly Fee",
        "Prepaid Electricity Recharge",
        "Home Utility Bundle Payment",
        "Natural Gas Meter Reading Fee",
        "Smart Meter Installation Fee",
        "Natural Gas Utility Bill",
        "Cairo Electricity Distribution Company Electricity Invoice",
        "Gas Utility Payment",
        "Router Rental Fee",
        "Internet Bill Noor ADSL",
        "Utility Deposit Refund Adjustment",
        "Broadband Internet Payment",
    ],
    "Fuel": [
        "Fuel at Chevron",
        "Misr Petroleum Petrol Refill",
        "Fuel Payment Petromin",
        "Gas Station TotalEnergies",
        "Chevron Fuel Purchase",
        "Mobil Petrol Refill",
        "Watanya Petroleum Gas Fill Up",
        "Misr Petroleum Full Tank",
        "Petromin Petrol Refill",
        "Watanya Petroleum Full Tank",
        "Gas Station Misr Petroleum",
        "Diesel Refill Mobil",
        "Fuel at WEPCO Fuel Station",
        "Fuel Payment Misr Petroleum",
        "Gas Station Chevron",
        "Gas Station Mobil",
        "Chevron Full Tank",
        "WEPCO Fuel Station Full Tank",
        "Diesel Refill Petromin",
        "Fuel Payment Watanya Petroleum",
        "TotalEnergies Petrol Refill",
        "Shell Full Tank",
        "Diesel Refill Misr Petroleum",
        "Diesel Refill Watanya Petroleum",
        "Fuel at Mobil",
        "Petromin Gas Fill Up",
        "Chevron Gas Fill Up",
        "Gas Station Petromin",
        "TotalEnergies Full Tank",
        "Gas Station Watanya Petroleum",
        "Fuel at Shell",
        "Misr Petroleum Fuel Purchase",
        "Petromin Full Tank",
        "Misr Petroleum Gas Fill Up",
        "Fuel at Misr Petroleum",
        "TotalEnergies Gas Fill Up",
        "Fuel Payment Shell",
        "Chevron Petrol Refill",
        "Watanya Petroleum Petrol Refill",
        "WEPCO Fuel Station Gas Fill Up",
        "Fuel at Watanya Petroleum",
        "Mobil Fuel Purchase",
        "Diesel Refill Shell",
        "Fuel Payment Chevron",
        "Shell Fuel Purchase",
        "Diesel Refill TotalEnergies",
        "Fuel Payment Mobil",
        "Gas Station WEPCO Fuel Station",
        "Diesel Refill Chevron",
        "Gas Station Shell",
    ],
    "Rent": [
        "Rent Payment Nasr City",
        "Rent Payment October",
        "Furnished Apartment Rent",
        "Co-working Space Rent",
        "Rent Payment September",
        "Studio Apartment Rent",
        "Rent Payment June",
        "Rent Payment May",
        "Rent Payment Giza Apartment",
        "Rent Payment Dokki Apartment",
        "Vacation Home Rent Payment",
        "Apartment Rent August",
        "Monthly Rent Payment",
        "Apartment Rent September",
        "Rent Payment Mohandessin Flat",
        "Rent Payment July",
        "Garage Rent Payment",
        "Rent Payment August",
        "Rent Payment April",
        "Rent Payment February",
        "Rent Transfer to Landlord",
        "Rent Payment 6th of October",
        "Office Rent Payment",
        "Rent Payment November",
        "Rent Payment Sheikh Zayed Villa",
        "Rent Payment Alexandria Apartment",
        "Apartment Rent October",
        "Monthly Lease Payment",
        "Apartment Rent Payment",
        "Warehouse Rent Payment",
        "Rent Payment Maadi Apartment",
        "Apartment Rent July",
        "Shop Rent Payment",
        "Apartment Rent June",
        "Rent Payment December",
        "Apartment Rent December",
        "Apartment Rent May",
        "Rent Payment March",
        "Rent Payment Downtown Flat",
        "Apartment Rent November",
        "Apartment Rent March",
        "Rent Payment Rehab City",
        "Rent Payment Zamalek Apartment",
        "Rent Payment January",
        "Rent Payment New Cairo Apartment",
        "Storage Unit Rent",
        "Apartment Rent February",
        "Apartment Rent January",
        "Rent Payment Heliopolis Flat",
        "Apartment Rent April",
    ],
    "Electronics": [
        "Dell Laptop Order",
        "Best Buy Purchase",
        "Samsung Galaxy S24 Order",
        "B.Tech Purchase",
        "2B Electronics Purchase",
        "2B Electronics Electronics Order",
        "iPhone 15 Purchase",
        "Compumarts Electronics Order",
        "B.Tech Gadget Purchase",
        "Xiaomi Phone Order",
        "LG Store Egypt Gadget Purchase",
        "Samsung Store Gadget Purchase",
        "Samsung Galaxy S24 Purchase",
        "iPad Air Order",
        "PlayStation 5 Purchase",
        "B.Tech Electronics Order",
        "Apple Store Electronics Order",
        "Khairy Electronics Gadget Purchase",
        "MacBook Pro Purchase",
        "Micro Center Gadget Purchase",
        "LG Store Egypt Electronics Order",
        "Dell Laptop Purchase",
        "Amazon Electronics Gadget Purchase",
        "Amazon Electronics Purchase",
        "iPad Air Purchase",
        "Sony Store Gadget Purchase",
        "LG Store Egypt Purchase",
        "LG TV Order",
        "Micro Center Purchase",
        "Apple Store Purchase",
        "Raya Electronics Electronics Order",
        "Amazon Electronics Electronics Order",
        "Sony Store Electronics Order",
        "Samsung Store Purchase",
        "Compumarts Purchase",
        "Compumarts Gadget Purchase",
        "Khairy Electronics Electronics Order",
        "2B Electronics Gadget Purchase",
        "Micro Center Electronics Order",
        "Samsung Store Electronics Order",
        "Raya Electronics Gadget Purchase",
        "LG TV Purchase",
        "Xiaomi Phone Purchase",
        "Sony Store Purchase",
        "MacBook Pro Order",
        "AirPods Pro Order",
        "Best Buy Gadget Purchase",
        "AirPods Pro Purchase",
        "Sony Headphones Order",
        "iPhone 15 Order",
    ],
    "Personal Care": [
        "Cleo Beauty Salon Purchase",
        "Spa Session Spa Center",
        "Skincare Purchase L'Occitane",
        "Haircut at Spa Center",
        "Makeup Purchase L'Occitane",
        "Haircut at The Body Shop",
        "Spa Session Cleo Beauty Salon",
        "Manicure Pedicure",
        "Hair Salon Purchase",
        "Skincare Purchase Sally Beauty",
        "Spa Session The Body Shop",
        "Sally Beauty Purchase",
        "Spa Session L'Occitane",
        "Haircut at MAC Cosmetics",
        "Makeup Purchase Spa Center",
        "Skincare Purchase MAC Cosmetics",
        "Haircut at Barber Shop",
        "Skincare Purchase Spa Center",
        "Spa Session Nails Studio",
        "Skincare Purchase Cleo Beauty Salon",
        "Haircut at Hair Salon",
        "Sephora Purchase",
        "Barber Shop Payment",
        "Makeup Purchase Sally Beauty",
        "Nails Studio Purchase",
        "Makeup Purchase MAC Cosmetics",
        "Spa Session Hair Salon",
        "Skincare Purchase Hair Salon",
        "Haircut at L'Occitane",
        "Spa Session Sally Beauty",
        "Spa Session MAC Cosmetics",
        "Barber Shop Purchase",
        "Haircut at Nails Studio",
        "Makeup Purchase Nails Studio",
        "MAC Cosmetics Purchase",
        "Makeup Purchase Hair Salon",
        "Spa Center Purchase",
        "L'Occitane Purchase",
        "Spa Session Barber Shop",
        "Makeup Purchase Sephora",
        "Makeup Purchase Cleo Beauty Salon",
        "Makeup Purchase Barber Shop",
        "Skincare Purchase Barber Shop",
        "Haircut at Sephora",
        "The Body Shop Purchase",
        "Makeup Purchase The Body Shop",
        "Spa Session Sephora",
        "Haircut at Sally Beauty",
        "Skincare Purchase The Body Shop",
        "Haircut at Cleo Beauty Salon",
    ],
    "Gifts": [
        "Flowers Order Talabat Gifts",
        "Gift Purchase Hallmark Store",
        "Toy Store Purchase",
        "Anniversary Gift Purchase",
        "Flower Store Online Order",
        "Flowers Order Flower Store",
        "Gift Purchase Interflora Egypt",
        "Gift for Husband",
        "Hallmark Store Online Order",
        "Flowers Order Bloomy's Flowers",
        "Toy Store Online Order",
        "Birthday Gift for Client",
        "Birthday Gift for Mom",
        "Gift for Dad",
        "Wedding Gift Purchase",
        "Gift Shop Purchase",
        "Chocolate Bar Online Order",
        "Gift for Friend",
        "Flowers Order Gift Shop",
        "Gift Purchase Talabat Gifts",
        "Talabat Gifts Online Order",
        "Gift Purchase Gift Shop",
        "Gift Purchase Toy Store",
        "Gift for Mom",
        "Gift for Brother",
        "Interflora Egypt Purchase",
        "Flowers Order Interflora Egypt",
        "Talabat Gifts Purchase",
        "Flowers Order Toy Store",
        "Bloomy's Flowers Purchase",
        "Gift Purchase Flower Store",
        "Gift for Client",
        "Birthday Gift for Husband",
        "Bloomy's Flowers Online Order",
        "Gift Shop Online Order",
        "Flower Store Purchase",
        "Interflora Egypt Online Order",
        "Flowers Order Chocolate Bar",
        "Chocolate Bar Purchase",
        "Flowers Order Hallmark Store",
        "Gift for Colleague",
        "Eid Gift Purchase",
        "Gift for Wife",
        "Birthday Gift for Sister",
        "Birthday Gift for Friend",
        "Hallmark Store Purchase",
        "Birthday Gift for Dad",
        "Gift Purchase Bloomy's Flowers",
        "Birthday Gift for Wife",
        "Gift for Sister",
    ],
}


# -----------------------------------------------------------------------
# 2. REALISTIC CATEGORY WEIGHTS
# -----------------------------------------------------------------------
CATEGORY_WEIGHTS = {
    "Food":           14,
    "Transport":      12,
    "Shopping":       10,
    "Groceries":      10,
    "Bills":           6,
    "Fuel":            6,
    "Entertainment":   6,
    "Healthcare":      5,
    "Subscriptions":   5,
    "Personal Care":   4,
    "Utilities":       4,
    "Gifts":           3,
    "Income":          3,
    "Electronics":     3,
    "Travel":          2,
    "Education":       2,
    "Insurance":       2,
    "Rent":            1.5,
    "Salary":          1.5,
    "Investment":      1.5,
}

CATEGORIES_LIST = list(CATEGORY_WEIGHTS.keys())
WEIGHTS_LIST = list(CATEGORY_WEIGHTS.values())

# -----------------------------------------------------------------------
# 3. REALISTIC AMOUNT RANGES PER CATEGORY (low, most_likely, high)
# -----------------------------------------------------------------------
AMOUNT_RANGES = {
    "Food":            (15,     120,    600),
    "Transport":       (10,      60,    400),
    "Shopping":        (50,     400,   4000),
    "Bills":           (50,     250,   1800),
    "Entertainment":   (20,     150,   1200),
    "Healthcare":      (50,     400,   4000),
    "Education":       (300,   3000,  20000),
    "Groceries":       (50,     350,   2500),
    "Income":          (300,   1500,   9000),
    "Travel":          (500,   3000,  18000),
    "Subscriptions":   (20,      90,    600),
    "Insurance":       (200,   1200,   6000),
    "Investment":      (1000,  8000,  60000),
    "Salary":          (5000, 15000,  45000),
    "Utilities":       (50,     300,   1500),
    "Fuel":            (50,     250,   1000),
    "Rent":            (3000, 10000,  28000),
    "Electronics":     (500,   4000,  35000),
    "Personal Care":   (50,     250,   1800),
    "Gifts":           (50,     300,   2500),
}

# -----------------------------------------------------------------------
# 4. TEXT AUGMENTATION: prefixes + noise suffixes
# -----------------------------------------------------------------------
PREFIXES = [
    "", "", "", "",              # frequent: no prefix at all (raw bank text)
    "Bought ", "Paid for ", "Transaction: ", "Expense - ", "Purchase - ",
    "POS ", "Payment for ", "Debit - ",
]

NOISE_SUFFIXES = [
    "", "", "",                  # frequent: no suffix
    " online", " card payment", " app", " receipt", " - confirmed",
    " (auto-debit)", " via card", " mobile app", " ref#",
    " - visa debit", " - mastercard", " e-payment", " POS purchase",
]

# -----------------------------------------------------------------------
# 5. CORE GENERATOR
# -----------------------------------------------------------------------
def _generate_amount(category: str) -> float:
    low, mode, high = AMOUNT_RANGES[category]
    return round(random.triangular(low, high, mode), 2)


def _build_description(category: str) -> str:
    base = random.choice(CATEGORIES[category])
    prefix = random.choice(PREFIXES)
    suffix = random.choice(NOISE_SUFFIXES)

    if suffix == " ref#":
        suffix = f" ref#{random.randint(10000, 999999)}"

    return f"{prefix}{base}{suffix}".strip()


def generate_data(n: int = 10000, label_noise_ratio: float = 0.03, verbose: bool = True):
    """
    Generate `n` synthetic Transaction rows, all attached to a dedicated
    training-only user (TRAINING_USERNAME) so your own account's
    Dashboard/History/Analysis/Budgets/exports stay untouched.
    """
    user, created = User.objects.get_or_create(
        username=TRAINING_USERNAME,
        defaults={"email": "ml-training@internal.local"},
    )
    if created and verbose:
        print(f"Created dedicated training user: '{TRAINING_USERNAME}'")

    # Create/fetch Category objects once
    category_objs = {}
    for cat in CATEGORIES_LIST:
        obj, _ = Category.objects.get_or_create(name=cat)
        category_objs[cat] = obj

    income_categories = {"Salary", "Income", "Investment"}

    transactions_to_create = []
    noisy_count = 0

    for _ in range(n):
        true_category = random.choices(CATEGORIES_LIST, weights=WEIGHTS_LIST, k=1)[0]

        description = _build_description(true_category)
        amount = _generate_amount(true_category)
        tx_type = "income" if true_category in income_categories else "expense"
        random_date = date.today() - timedelta(days=random.randint(0, 365))

        if random.random() < label_noise_ratio:
            wrong_choices = [c for c in CATEGORIES_LIST if c != true_category]
            stored_category = random.choice(wrong_choices)
            noisy_count += 1
        else:
            stored_category = true_category

        transactions_to_create.append(
            Transaction(
                user=user,
                description=description,
                amount=amount,
                type=tx_type,
                category=category_objs[stored_category],
                date=random_date,
            )
        )

    Transaction.objects.bulk_create(transactions_to_create, batch_size=1000)

    if verbose:
        print(f"{n} transactions generated successfully!")
        print(f"Label noise applied to {noisy_count} rows ({noisy_count / n:.1%})")
        print(f"All rows attached to training user '{TRAINING_USERNAME}' "
              f"(id={user.id}) — your real account is untouched.")


def delete_training_data(verbose: bool = True):
    """
    Optional cleanup: removes ALL synthetic rows (and the dedicated
    training user) once you're done training and no longer need them
    sitting in the DB. Safe to run any time — never touches real users.
    """
    try:
        user = User.objects.get(username=TRAINING_USERNAME)
    except User.DoesNotExist:
        if verbose:
            print("No training user found — nothing to delete.")
        return

    count, _ = Transaction.objects.filter(user=user).delete()
    user.delete()
    if verbose:
        print(f"Deleted {count} synthetic transactions and the training user.")


if __name__ == "__main__":
    generate_data(10000)